// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/AddonListTab/ListAddonsMenu.layout

class WEXT_ListAddonsMenuWidgets
{
	static const ResourceName s_sLayout = "{5242DD0FBCE21DF5}UI/AddonListTab/ListAddonsMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	SizeLayoutWidget m_AddonsListPanel;

	ScrollLayoutWidget m_AddonsListScroll;

	VerticalLayoutWidget m_AddonsList;

	OverlayWidget m_AddonInfoPanel;
	SCR_AddonDetailsPanelComponent m_AddonInfoPanelComponent;

	bool Init(Widget root)
	{
		m_AddonsListPanel = SizeLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_AddonsListPanel"));

		m_AddonsListScroll = ScrollLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_AddonsListPanel.VerticalLayout0.Content.Scroll"));

		m_AddonsList = VerticalLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_AddonsListPanel.VerticalLayout0.Content.Scroll.m_AddonsList"));

		m_AddonInfoPanel = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.RightPanel.VerticalLayout0.Content.m_AddonInfoPanel"));
		m_AddonInfoPanelComponent = SCR_AddonDetailsPanelComponent.Cast(m_AddonInfoPanel.FindHandler(SCR_AddonDetailsPanelComponent));

		return true;
	}
}
